language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

gemfile:
  - gemfiles/Gemfile.rails-3.x
  - gemfiles/Gemfile.rails-4.x

# Set up and start Faye Server before tests are run
before_script:
  - cp test/travis/sync.yml config/sync.yml
  - cp test/travis/sync.ru sync.ru
  - thin start -R sync.ru -p 9292 -t 1 2>&1 > test.log &
